---
deployment:
  tasks:
    - export DEPLOYPATH=/home/investop/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
